Algoritmo "Concatenação"
// Descrição   : Concatenação
// Autor(a)    : Carol
// Data atual  : 11/03/2022
Var
// Seção de Declarações das variáveis 
   nome: caractere
   numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o nome:")
   leia(nome)
   escreval("Digite o numero")
   leia(numero)
   
   escreval(nome, " : ", numero, 15)

Fimalgoritmo