Algoritmo "Operadores Relacionais"
// Descrição   : Operadores Relacionais
// Autor(a)    : Carol
// Data atual  : 09/03/2022
Var
// Seção de Declarações das variáveis 
   nota01, nota02: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota01 := 10
   nota02 := 15
   se(nota01 = nota02)entao
     escreval("Nota01 é diferente")
   senao
     escreval("Nota01 é igual")
   fimse
Fimalgoritmo